globalThis.SDS_RECORDS = (globalThis.SDS_RECORDS || []).concat([
  {
    "id": "si-cij9090-make-up",
    "name": "SI-CIJ9090 Make-Up",
    "company": "Squid Ink",
    "product_code": "SI-CIJ9090",
    "use": "Coder",
    "sds_number": "N/A",
    "sds_version": "1.2",
    "issue_date": "08/11/2015",
    "revision_date": "06/15/2020",
    "supersedes_date": "N/A",
    "composition": "butanone / ethyl (S)-2-hydroxypropionate, ethyl L-lactate, ethyl-(S)-lactate",
    "hfrp_info": "1/3/0/0",
    "sds_url": "https://drive.google.com/drive/folders/1UEq_4ifSSUOTW7ufJqijrt9dSyCHvpun",
    "sds_reference": "https://drive.google.com/drive/folders/1UEq_4ifSSUOTW7ufJqijrt9dSyCHvpun",
    "updated_at": "2026-06-05"
  },
  {
    "id": "3m-silicone-spray",
    "name": "3M Silicone Spray",
    "company": "3M",
    "product_code": "62-4699-4930-9 (8)",
    "use": "Lubricant",
    "sds_number": "N/A",
    "sds_version": "5.0",
    "issue_date": "05/24/2018",
    "revision_date": "07/01/2016",
    "supersedes_date": "07/01/2016",
    "composition": "Acetone, Hydrotreated Light Naphtha (Petroleum), Propane, Poly(Dimethylsiloxane, Methylcylohexane, Solvent Naphtha",
    "hfrp_info": "2/4/0/0",
    "sds_url": "https://www.uline.com/PDF/SS-18768.pdf",
    "sds_reference": "https://www.uline.com/PDF/SS-18768.pdf",
    "updated_at": "2026-06-05"
  },
  {
    "id": "rapid-tap-cutting-oil",
    "name": "Rapid Tap Cutting Oil",
    "company": "Relton Corporation",
    "product_code": "N/A",
    "use": "Lubricant",
    "sds_number": "N/A",
    "sds_version": "1.0",
    "issue_date": "03/30/2015",
    "revision_date": "New Issue",
    "supersedes_date": "N/A",
    "composition": "Mineral oil (70-90%), C14-C16 chlorinated paraffin (<40%), Calcium sulfonate (2-3%)",
    "hfrp_info": "1/1/0/C",
    "sds_url": "https://sojoindustries0.sharepoint.com/:b:/s/SojoSharedDocuments/EbfO-v_LeUVGh7iQZfYP8H0Bg0qFNk5YFUyjiuHDqEfHwA?e=Vuu1Vl",
    "sds_reference": "https://sojoindustries0.sharepoint.com/:b:/s/SojoSharedDocuments/EbfO-v_LeUVGh7iQZfYP8H0Bg0qFNk5YFUyjiuHDqEfHwA?e=Vuu1Vl",
    "updated_at": "2026-06-05"
  },
  {
    "id": "spray-on-food-grade-silicone-lubricant",
    "name": "Spray-on Food Grade Silicone Lubricant",
    "company": "Sprayon Products",
    "product_code": "S00210",
    "use": "Lubricant",
    "sds_number": "N/A",
    "sds_version": "1",
    "issue_date": "03/13/2015",
    "revision_date": "N/A",
    "supersedes_date": "N/A",
    "composition": "Hexane (42%), 2-Methylpentane (19.4%), Propane (15%), 3-Methylpentane (7.2%)",
    "hfrp_info": "2/4/0/0",
    "sds_url": "https://sojoindustries0.sharepoint.com/:b:/s/SojoSharedDocuments/EQXbYCMOjjZJuVk194M89-MBFerINpXAqnkF-XfnuA1jZQ?e=njAQch",
    "sds_reference": "https://sojoindustries0.sharepoint.com/:b:/s/SojoSharedDocuments/EQXbYCMOjjZJuVk194M89-MBFerINpXAqnkF-XfnuA1jZQ?e=njAQch",
    "updated_at": "2026-06-05"
  },
  {
    "id": "markem-imaje-320-cleaner",
    "name": "Markem Imaje 320 Cleaner",
    "company": "Markem-Imaje",
    "product_code": "80000343204B",
    "use": "Coder",
    "sds_number": "UN1993",
    "sds_version": "4",
    "issue_date": "04/22/2026",
    "revision_date": "04/22/2026",
    "supersedes_date": "",
    "composition": "Isopropyl Alcohol (~60-70%), Ethyl Acetate (~30-40%)",
    "hfrp_info": "2/3/0/0",
    "sds_url": "https://sojoindustries0.sharepoint.com/sites/SojoSharedDocuments/Shared%20Documents/SQF%20&%20QPI%20Folder/Archive/MSDS%20Information/Markem%20Imaje%20320%20Cleaner.pdf?CT=1778009111383&OR=ItemsView",
    "sds_reference": "https://sojoindustries0.sharepoint.com/sites/SojoSharedDocuments/Shared%20Documents/SQF%20&%20QPI%20Folder/Archive/MSDS%20Information/Markem%20Imaje%20320%20Cleaner.pdf?CT=1778009111383&OR=ItemsView",
    "updated_at": "2026-06-05"
  },
  {
    "id": "sprayon-machine-oil-lu700-h1-10-oz-aerosol-can-iso-grade-32",
    "name": "SPRAYON Machine Oil: LU700, H1, 10 oz, Aerosol Can, ISO Grade 32",
    "company": "Sprayon Products",
    "product_code": "S00700",
    "use": "Machine Maintenance",
    "sds_number": "N/A",
    "sds_version": "1",
    "issue_date": "05/29/2015",
    "revision_date": "N/A",
    "supersedes_date": "N/A",
    "composition": "Aliphatic Solvent (67.5%), Paraffinic Mineral Oil (30%)",
    "hfrp_info": "2/4/0/0",
    "sds_url": "https://www.grainger.com/sds/pdf/220785.pdf",
    "sds_reference": "https://www.grainger.com/sds/pdf/220785.pdf",
    "updated_at": "2026-06-05"
  },
  {
    "id": "lps-detex-foodlube-sugar-dissolving-fluid",
    "name": "LPS DETEX FoodLube Sugar Dissolving Fluid",
    "company": "ITW Pro Brands",
    "product_code": "57716 / 57728 / C57701",
    "use": "Machine Maintenance",
    "sds_number": "57716",
    "sds_version": "1.2",
    "issue_date": "6/14/2019",
    "revision_date": "2/10/2023",
    "supersedes_date": "5/22/2018",
    "composition": "Petroleum lubricants, corrosion inhibitors",
    "hfrp_info": "1/1/0/0",
    "sds_url": "https://www.itwprobrands.com/files/techdatasheets/LPSDETEXFOODLUBESugarDissolvingFluid-.pdf",
    "sds_reference": "https://www.itwprobrands.com/files/techdatasheets/LPSDETEXFOODLUBESugarDissolvingFluid-.pdf",
    "updated_at": "2026-06-05"
  },
  {
    "id": "klean-strip-denatured-alcohol",
    "name": "Klean-Strip Denatured Alcohol",
    "company": "W.M. Barr / Klean-Strip",
    "product_code": "GSL26 / QSL26 series",
    "use": "Machine Maintenance",
    "sds_number": "GKSL26",
    "sds_version": "3.1",
    "issue_date": "3/19/2020",
    "revision_date": "8/10/2023",
    "supersedes_date": "1/5/2018",
    "composition": "Ethanol, Methanol, Methyl Isobutyl Ketone",
    "hfrp_info": "2/3/0/0",
    "sds_url": "https://kleanstrip.com/heating-fuels/denatured-alcohol/",
    "sds_reference": "https://kleanstrip.com/heating-fuels/denatured-alcohol/",
    "updated_at": "2026-06-05"
  },
  {
    "id": "wd-40-ez-reach",
    "name": "WD-40 EZ-REACH",
    "company": "WD-40 Company",
    "product_code": "EZ-REACH",
    "use": "Machine Maintenance",
    "sds_number": "491567",
    "sds_version": "2",
    "issue_date": "4/8/2021",
    "revision_date": "1/12/2024",
    "supersedes_date": "9/15/2019",
    "composition": "Petroleum distillates, base oils, CO2 propellant",
    "hfrp_info": "12/0/0",
    "sds_url": "https://www.wd40.com/products/ez-reach/",
    "sds_reference": "https://www.wd40.com/products/ez-reach/",
    "updated_at": "2026-06-05"
  }
]);
