globalThis.SDS_RECORDS = (globalThis.SDS_RECORDS || []).concat([
  {
    "id": "crc-qd-electronic-cleaner",
    "name": "CRC QD Electronic Cleaner",
    "company": "CRC Industries",
    "product_code": "5103",
    "use": "Machine Maintenance",
    "sds_number": "5103",
    "sds_version": "5.4",
    "issue_date": "11/2/2020",
    "revision_date": "9/18/2023",
    "supersedes_date": "7/11/2019",
    "composition": "Hexane, ethanol, CO2",
    "hfrp_info": "2/4/0/0",
    "sds_url": "https://www.crcindustries.com/qd-174-electronic-cleaner-11-wt-oz/",
    "sds_reference": "https://www.crcindustries.com/qd-174-electronic-cleaner-11-wt-oz/",
    "updated_at": "2026-06-05"
  },
  {
    "id": "chemtronics-electro-wash-px",
    "name": "Chemtronics Electro-Wash PX",
    "company": "Chemtronics",
    "product_code": "ES1605 / ES1610",
    "use": "Machine Maintenance",
    "sds_number": "ES1605",
    "sds_version": "4",
    "issue_date": "8/16/2019",
    "revision_date": "12/1/2022",
    "supersedes_date": "4/20/2018",
    "composition": "n-Hexane, IPA, hydrocarbon propellants",
    "hfrp_info": "2/4/0/0",
    "sds_url": "https://www.chemtronics.com/electro-wash-px",
    "sds_reference": "https://www.chemtronics.com/electro-wash-px",
    "updated_at": "2026-06-05"
  },
  {
    "id": "ags-sil-glyde-silicone-compound",
    "name": "AGS Sil-Glyde Silicone Compound",
    "company": "American Grease Stick",
    "product_code": "BK-4",
    "use": "Machine Maintenance",
    "sds_number": "BK-4",
    "sds_version": "2.3",
    "issue_date": "2/14/2018",
    "revision_date": "6/22/2021",
    "supersedes_date": "10/9/2016",
    "composition": "Silicone compounds, petroleum oils",
    "hfrp_info": "1/1/0/0",
    "sds_url": "https://agscompany.com/product/sil-glyde-silicone-brake-lubricant/",
    "sds_reference": "https://agscompany.com/product/sil-glyde-silicone-brake-lubricant/",
    "updated_at": "2026-06-05"
  },
  {
    "id": "crc-3-36-multi-purpose-lubricant",
    "name": "CRC 3-36 Multi-Purpose Lubricant",
    "company": "CRC Industries",
    "product_code": "3005",
    "use": "Machine Maintenance",
    "sds_number": "3005",
    "sds_version": "3.8",
    "issue_date": "1/27/2021",
    "revision_date": "2/5/2024",
    "supersedes_date": "3/18/2019",
    "composition": "Petroleum distillates, mineral oil",
    "hfrp_info": "1/2/0/0",
    "sds_url": "https://www.crcindustries.com/3-36-multi-purpose-lubricant-and-corrosion-inhibitor-11-wt-oz/",
    "sds_reference": "https://www.crcindustries.com/3-36-multi-purpose-lubricant-and-corrosion-inhibitor-11-wt-oz/",
    "updated_at": "2026-06-05"
  },
  {
    "id": "bernzomatic-butane-fuel",
    "name": "Bernzomatic Butane Fuel",
    "company": "Worthington Enterprises",
    "product_code": "BF56",
    "use": "Machine Maintenance",
    "sds_number": "BF56",
    "sds_version": "2.1",
    "issue_date": "5/10/2019",
    "revision_date": "7/14/2023",
    "supersedes_date": "8/25/2017",
    "composition": "Butane",
    "hfrp_info": "1/4/0/0",
    "sds_url": "https://www.bernzomatic.com/Products/Fuel-Cylinders/Butane/BF56",
    "sds_reference": "https://www.bernzomatic.com/Products/Fuel-Cylinders/Butane/BF56",
    "updated_at": "2026-06-05"
  },
  {
    "id": "gojo-natural-orange-pumice-hand-cleaner",
    "name": "GOJO Natural Orange Pumice Hand Cleaner",
    "company": "GOJO Industries",
    "product_code": "0955 / 0956",
    "use": "Cleaner",
    "sds_number": "955",
    "sds_version": "1.9",
    "issue_date": "6/1/2020",
    "revision_date": "3/29/2023",
    "supersedes_date": "11/12/2018",
    "composition": "Citrus solvents, pumice, surfactants",
    "hfrp_info": "1/0/0/0",
    "sds_url": "https://www.gojo.com/en/Product/0955-04",
    "sds_reference": "https://www.gojo.com/en/Product/0955-04",
    "updated_at": "2026-06-05"
  },
  {
    "id": "great-stuff-fireblock-insulating-foam-sealant",
    "name": "Great Stuff Fireblock Insulating Foam Sealant",
    "company": "DuPont",
    "product_code": "Fireblock",
    "use": "Machine Maintenance",
    "sds_number": "FB136",
    "sds_version": "6.2",
    "issue_date": "9/17/2021",
    "revision_date": "1/30/2024",
    "supersedes_date": "5/6/2020",
    "composition": "Diphenylmethane diisocyanate (MDI), propane",
    "hfrp_info": "2/4/1/0",
    "sds_url": "https://www.greatstuff.dupont.com/products/greatstuff-fireblock.html",
    "sds_reference": "https://www.greatstuff.dupont.com/products/greatstuff-fireblock.html",
    "updated_at": "2026-06-05"
  },
  {
    "id": "loctite-threadlocker-thread-smart",
    "name": "Loctite Threadlocker / Thread Smart",
    "company": "Henkel",
    "product_code": "242",
    "use": "Machine Maintenance",
    "sds_number": "242",
    "sds_version": "5",
    "issue_date": "10/13/2020",
    "revision_date": "11/8/2023",
    "supersedes_date": "2/21/2019",
    "composition": "Dimethacrylate ester, cumene hydroperoxide",
    "hfrp_info": "2/1/0/0",
    "sds_url": "https://www.henkel-adhesives.com/us/en/product/threadlockers/loctite_2420.html",
    "sds_reference": "https://www.henkel-adhesives.com/us/en/product/threadlockers/loctite_2420.html",
    "updated_at": "2026-06-05"
  },
  {
    "id": "lubriplate-grease",
    "name": "Lubriplate Grease",
    "company": "Lubriplate Lubricants Company",
    "product_code": "630-AA",
    "use": "Machine Maintenance",
    "sds_number": "630-AA",
    "sds_version": "2.7",
    "issue_date": "1/4/2019",
    "revision_date": "8/19/2022",
    "supersedes_date": "6/15/2017",
    "composition": "Petroleum oil, lithium soap, additives",
    "hfrp_info": "1/1/0/0",
    "sds_url": "https://www.lubriplate.com/Products/Greases/Multi-Purpose-Greases/630-Series/630-AA",
    "sds_reference": "https://www.lubriplate.com/Products/Greases/Multi-Purpose-Greases/630-Series/630-AA",
    "updated_at": "2026-06-05"
  }
]);
