globalThis.SDS_RECORDS = (globalThis.SDS_RECORDS || []).concat([
  {
    "id": "all-purpose-cleaner-spray",
    "name": "All Purpose Cleaner Spray",
    "company": "ULINE",
    "product_code": "S-19455",
    "use": "Office Cleaning",
    "sds_number": "N/A",
    "sds_version": "1.0",
    "issue_date": "03/07/2018",
    "revision_date": "03/07/2018",
    "supersedes_date": "N/A",
    "composition": "2-(2-butoxyethoxy)ethanol",
    "hfrp_info": "0/0/0/B",
    "sds_url": "https://www.uline.com/PDF/SS-19455.pdf",
    "sds_reference": "https://www.uline.com/PDF/SS-19455.pdf",
    "updated_at": "2026-06-08"
  },
  {
    "id": "uline-all-purpose-cleaner-refill",
    "name": "Uline All-Purpose Cleaner Refill",
    "company": "ULINE",
    "product_code": "S-19456",
    "use": "Office Cleaning",
    "sds_number": "N/A",
    "sds_version": "1.0",
    "issue_date": "04/23/2021",
    "revision_date": "N/A",
    "supersedes_date": "N/A",
    "composition": "2-(2-butoxyethoxy)ethanol",
    "hfrp_info": "0/0/0/B",
    "sds_url": "https://img.uline.com/is/content/uline/SS-19456pdf",
    "sds_reference": "https://img.uline.com/is/content/uline/SS-19456pdf",
    "updated_at": "2026-06-08"
  },
  {
    "id": "uline-air-freshener-cool-linen",
    "name": "Uline Air Freshener - Cool Linen",
    "company": "ULINE",
    "product_code": "S-17147",
    "use": "Office Cleaning",
    "sds_number": "N/A",
    "sds_version": "1.0",
    "issue_date": "11/18/2022",
    "revision_date": "N/A",
    "supersedes_date": "N/A",
    "composition": "N/A",
    "hfrp_info": "0/1/0/0",
    "sds_url": "https://www.uline.com/PDF/SS-17147.pdf",
    "sds_reference": "https://www.uline.com/PDF/SS-17147.pdf",
    "updated_at": "2026-06-08"
  },
  {
    "id": "clorox-germicidal-bleach-concentrated",
    "name": "Clorox® Germicidal Bleach Concentrated",
    "company": "S.C. Johnson & Son, Inc.",
    "product_code": "N/A",
    "use": "Office Cleaning",
    "sds_number": "N/A",
    "sds_version": "2.0",
    "issue_date": "05/08/2020",
    "revision_date": "05/15/2020",
    "supersedes_date": "N/A",
    "composition": "Sodium hypochlorite",
    "hfrp_info": "3/0/0/X",
    "sds_url": "https://www.thecloroxcompany.com/wp-content/uploads/2020/06/CloroxPro%C2%AE-Clorox%C2%AE-Germicidal-Bleach_Multilingual2.pdf",
    "sds_reference": "https://www.thecloroxcompany.com/wp-content/uploads/2020/06/CloroxPro%C2%AE-Clorox%C2%AE-Germicidal-Bleach_Multilingual2.pdf",
    "updated_at": "2026-06-08"
  },
  {
    "id": "uline-toilet-bowl-cleaner",
    "name": "Uline Toilet Bowl Cleaner",
    "company": "ULINE",
    "product_code": "S-24321",
    "use": "Office Cleaning",
    "sds_number": "N/A",
    "sds_version": "1.0",
    "issue_date": "12/09/2021",
    "revision_date": "N/A",
    "supersedes_date": "N/A",
    "composition": "Hydrochloric Acid",
    "hfrp_info": "3/0/0/0",
    "sds_url": "https://img.uline.com/is/content/uline/SS-24321pdf",
    "sds_reference": "https://img.uline.com/is/content/uline/SS-24321pdf",
    "updated_at": "2026-06-08"
  },
  {
    "id": "uline-glass-cleaner",
    "name": "Uline Glass Cleaner",
    "company": "ULINE",
    "product_code": "S-19452",
    "use": "Office Cleaning",
    "sds_number": "N/A",
    "sds_version": "1.0",
    "issue_date": "06/07/2021",
    "revision_date": "N/A",
    "supersedes_date": "N/A",
    "composition": "2-Propanol, Surfactant Blend, Ammonia",
    "hfrp_info": "0/0/0/0",
    "sds_url": "https://img.uline.com/is/content/uline/SS-19452pdf",
    "sds_reference": "https://img.uline.com/is/content/uline/SS-19452pdf",
    "updated_at": "2026-06-08"
  },
  {
    "id": "uline-multi-purpose-cleaner-lavender",
    "name": "Uline Multi-Purpose Cleaner - Lavender",
    "company": "ULINE",
    "product_code": "S-19454",
    "use": "Office Cleaning",
    "sds_number": "N/A",
    "sds_version": "1.0",
    "issue_date": "01/28/2021",
    "revision_date": "N/A",
    "supersedes_date": "N/A",
    "composition": "Surfactant Blend",
    "hfrp_info": "2/0/0/0",
    "sds_url": "https://img.uline.com/is/content/uline/SS-19454pdf",
    "sds_reference": "https://img.uline.com/is/content/uline/SS-19454pdf",
    "updated_at": "2026-06-08"
  },
  {
    "id": "30-secondsmold-mildew-remover",
    "name": "30 Seconds Mold & Mildew Remover",
    "company": "30 Seconds Cleaners",
    "product_code": "30S110",
    "use": "Office Cleaning",
    "sds_number": "N/A",
    "sds_version": "1.0",
    "issue_date": "01/10/2023",
    "revision_date": "N/A",
    "supersedes_date": "N/A",
    "composition": "Sodium hypochlorite",
    "hfrp_info": "3/0/0/0",
    "sds_url": "https://30secondscleaners.com/mwdownloads/download/link/id/2308",
    "sds_reference": "https://30secondscleaners.com/mwdownloads/download/link/id/2308",
    "updated_at": "2026-06-08"
  },
  {
    "id": "orange-sol-multi-use-citrus-solvent",
    "name": "ORANGE-SOL: Multi-Use Citrus Solvent",
    "company": "Orange-Sol",
    "product_code": "N/A",
    "use": "General Cleaning",
    "sds_number": "50026-001",
    "sds_version": "2.0",
    "issue_date": "04/03/1992",
    "revision_date": "02/07/2002",
    "supersedes_date": "04/03/1992",
    "composition": "N/A",
    "hfrp_info": "0/2/0/0",
    "sds_url": "",
    "sds_reference": "No verified public SDS link found; original reference was MS-CC-DMU.pdf",
    "updated_at": "2026-06-08"
  }
]);