globalThis.SDS_RECORDS = (globalThis.SDS_RECORDS || []).concat([
  {
    "id": "simple-green-industrial-cleaner-degreaser",
    "name": "Simple Green® Industrial Cleaner & Degreaser",
    "company": "Sunshine Makers, Inc.",
    "product_code": "43318000003",
    "use": "Machine Cleaning",
    "sds_number": "13008-21A",
    "sds_version": "N/A",
    "issue_date": "06/03/2021",
    "revision_date": "N/A",
    "supersedes_date": "05/31/2018",
    "composition": "C9-11 Alcohols Ethoxylated",
    "hfrp_info": "0/0/0/B",
    "sds_url": "https://cdn.simplegreen.com/downloads/SDS_EN-US_SimpleGreenIndustrialCleanerDegreaser.pdf",
    "sds_reference": "https://cdn.simplegreen.com/downloads/SDS_EN-US_SimpleGreenIndustrialCleanerDegreaser.pdf",
    "updated_at": "2026-06-05"
  },
  {
    "id": "softsoap-antibacterial-liquid-soap-hand-crisp-clean",
    "name": "SOFTSOAP ANTIBACTERIAL LIQUID SOAP - HAND CRISP CLEAN",
    "company": "Colgate-Palmolive Co",
    "product_code": "2E+11",
    "use": "Office Cleaning",
    "sds_number": "6.6E+11",
    "sds_version": "1.1",
    "issue_date": "N/A",
    "revision_date": "04/05/2016",
    "supersedes_date": "N/A",
    "composition": "CETRIMONIUM CHLORIDE",
    "hfrp_info": "3/1/0/0",
    "sds_url": "http://sds.staples.com/msds/789230.pdf",
    "sds_reference": "http://sds.staples.com/msds/789230.pdf",
    "updated_at": "2026-06-05"
  },
  {
    "id": "ultra-palmolive-antibacterial-dish-liquid",
    "name": "ULTRA PALMOLIVE ANTIBACTERIAL DISH LIQUID",
    "company": "Colgate-Palmolive Co",
    "product_code": "2E+11",
    "use": "Office Cleaning",
    "sds_number": "6.6E+11",
    "sds_version": "1.6",
    "issue_date": "06/09/2016",
    "revision_date": "06/17/2019",
    "supersedes_date": "N/A",
    "composition": "Sodium Laureth Sulfate",
    "hfrp_info": "3/1/0/0",
    "sds_url": "https://content.oppictures.com/Master_Images/Master_PDF_Files/CPC45038_SDS.PDF",
    "sds_reference": "https://content.oppictures.com/Master_Images/Master_PDF_Files/CPC45038_SDS.PDF",
    "updated_at": "2026-06-05"
  },
  {
    "id": "ultra-shine-dishwashing-liquid-lemon",
    "name": "Ultra Shine Dishwashing Liquid-Lemon",
    "company": "Ultra Soap International",
    "product_code": "N/A",
    "use": "Office Cleaning",
    "sds_number": "112000",
    "sds_version": "N/A",
    "issue_date": "N/A",
    "revision_date": "04/29/2016",
    "supersedes_date": "05/09/2015",
    "composition": "Sodium Laureth Sulfate",
    "hfrp_info": "3/1/0/0",
    "sds_url": "http://ultrasoap.com/assets/ultra-sds-ultra-shine-lemon-dish.pdf",
    "sds_reference": "http://ultrasoap.com/assets/ultra-sds-ultra-shine-lemon-dish.pdf",
    "updated_at": "2026-06-05"
  },
  {
    "id": "windex-original-glass-cleaner",
    "name": "WINDEX® ORIGINAL GLASS CLEANER",
    "company": "S.C. Johnson & Son, Inc.",
    "product_code": "N/A",
    "use": "Office Cleaning",
    "sds_number": "3.5E+11",
    "sds_version": "1.0",
    "issue_date": "09/06/2016",
    "revision_date": "N/A",
    "supersedes_date": "N/A",
    "composition": "N/A",
    "hfrp_info": "1/0/0/0",
    "sds_url": "https://beta.lakeland.edu/AboutUs/MSDS/PDFs/3258/Windex%20Original%20Glass%20Cleaner%20(SC%20Johnson)%201-23-18.pdf",
    "sds_reference": "https://beta.lakeland.edu/AboutUs/MSDS/PDFs/3258/Windex%20Original%20Glass%20Cleaner%20(SC%20Johnson)%201-23-18.pdf",
    "updated_at": "2026-06-05"
  },
  {
    "id": "a118-4-additive-for-markem-9450-coders",
    "name": "A118-4 Additive for Markem 9450 Coders",
    "company": "Markem Imaje",
    "product_code": "A118-4",
    "use": "Coder",
    "sds_number": "UN1193",
    "sds_version": "0.0",
    "issue_date": "07/13/2022",
    "revision_date": "07/13/2022",
    "supersedes_date": "N/A",
    "composition": "Methyl ethyl ketone",
    "hfrp_info": "1/3/0/0",
    "sds_url": "https://www.markem-imaje.com/services-support/safety-data-sheets",
    "sds_reference": "https://www.markem-imaje.com/services-support/safety-data-sheets",
    "updated_at": "2026-06-05"
  },
  {
    "id": "mb175-4-ink-for-markem-9450-coders",
    "name": "MB175-4 Ink for Markem 9450 Coders",
    "company": "Markem Imaje",
    "product_code": "MB175-4",
    "use": "Coder",
    "sds_number": "UN1210",
    "sds_version": "2.0",
    "issue_date": "08/18/2022",
    "revision_date": "07/13/2022",
    "supersedes_date": "N/A",
    "composition": "Methyl ethyl ketone",
    "hfrp_info": "1/3/0/0",
    "sds_url": "https://www.markem-imaje.com/services-support/safety-data-sheets",
    "sds_reference": "https://www.markem-imaje.com/services-support/safety-data-sheets",
    "updated_at": "2026-06-05"
  },
  {
    "id": "si-cij9020-black-ink",
    "name": "SI-CIJ9020 Black Ink",
    "company": "Squid Ink",
    "product_code": "SI-CIJ9020",
    "use": "Coder",
    "sds_number": "N/A",
    "sds_version": "1.2",
    "issue_date": "02/25/2015",
    "revision_date": "06/15/2020",
    "supersedes_date": "N/A",
    "composition": "butanone / 1-methoxy-2-propanol",
    "hfrp_info": "1/3/0/0",
    "sds_url": "https://drive.google.com/drive/folders/1UEq_4ifSSUOTW7ufJqijrt9dSyCHvpun",
    "sds_reference": "https://drive.google.com/drive/folders/1UEq_4ifSSUOTW7ufJqijrt9dSyCHvpun",
    "updated_at": "2026-06-05"
  },
  {
    "id": "si-cij9030-black-ink",
    "name": "SI-CIJ9030 Black Ink",
    "company": "Squid Ink",
    "product_code": "SI-CIJ9030",
    "use": "Coder",
    "sds_number": "N/A",
    "sds_version": "1.0",
    "issue_date": "12/05/2017",
    "revision_date": "12/05/2017",
    "supersedes_date": "N/A",
    "composition": "butanone / ethyl methyl ketone",
    "hfrp_info": "2/3/0/0",
    "sds_url": "https://drive.google.com/drive/folders/1UEq_4ifSSUOTW7ufJqijrt9dSyCHvpun",
    "sds_reference": "https://drive.google.com/drive/folders/1UEq_4ifSSUOTW7ufJqijrt9dSyCHvpun",
    "updated_at": "2026-06-05"
  }
]);
